"""Description of the migration

Revision ID: 00d91709cf89
Revises: af673733162b
Create Date: 2025-03-05 15:39:07.996617

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00d91709cf89'
down_revision = 'af673733162b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_description', sa.String(length=255), nullable=True))
        batch_op.alter_column('phone_number',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=False)
        batch_op.drop_column('Project_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Project_description', mysql.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=15),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('project_description')

    # ### end Alembic commands ###
